/** Original bilingual practice, separate from grounded object-word counts. */
export interface SceneConversation {
  readonly title: string;
  readonly roles: readonly [string, string];
  readonly lines: readonly (readonly [string, string])[];
}

export const SCENE_CONVERSATIONS: Readonly<Record<string, readonly SceneConversation[]>> = {
  "security-checkpoint": [
    { title: "确认安检要求", roles: ["旅客", "安检员"], lines: [
      ["Which queue should I join for this checkpoint?", "这个安检口我应该排哪一队？"],
      ["Please join the queue beside the blue sign.", "请排在蓝色标牌旁的队伍里。"],
      ["Do I need to take my laptop out of its case here?", "在这里需要把笔记本电脑从包里拿出来吗？"],
      ["Please follow the instructions displayed at this lane.", "请按这条通道上显示的要求操作。"],
      ["I didn't catch the last instruction. Could you repeat it?", "最后一条要求我没听清，您能再说一次吗？"],
      ["Of course. Please wait here until I call you forward.", "当然，请在这里等我叫您向前走。"],
    ] },
    { title: "取回物品与寻求协助", roles: ["旅客", "安检员"], lines: [
      ["My tray is still on the conveyor. Should I wait here?", "我的托盘还在传送带上，我在这里等吗？"],
      ["Yes, please keep the exit clear while you wait.", "是的，等候时请不要挡住出口。"],
      ["I think I left my watch in another tray.", "我可能把手表落在另一个托盘里了。"],
      ["Can you describe the watch and the tray it was in?", "您能描述一下手表和放它的托盘吗？"],
      ["It has a silver face and a dark leather strap.", "它是银色表盘，配深色皮表带。"],
      ["Stay beside this counter while I check for you.", "请在这个柜台旁等候，我帮您查看。"],
    ] },
  ],
  "aircraft-cabin": [
    { title: "找座位与放行李", roles: ["乘客", "乘务员"], lines: [
      ["Could you help me find seat eighteen C?", "能帮我找一下十八排C座吗？"],
      ["It's the aisle seat on your left, two rows ahead.", "在前面两排，您左侧靠过道的位置。"],
      ["The overhead locker above my seat looks full.", "我座位上方的行李架看起来满了。"],
      ["Let me find a suitable space for your bag.", "我来给您的包找个合适的位置。"],
      ["Could you show me how to adjust this seat belt?", "您能示范一下如何调节这条安全带吗？"],
      ["Certainly. Keep the aisle clear while I help you.", "当然，我帮您时请不要挡住过道。"],
    ] },
    { title: "机上服务与沟通", roles: ["乘客", "乘务员"], lines: [
      ["May I have some still water when you have a moment?", "您方便的时候能给我一些不含气的水吗？"],
      ["Certainly. Would you like a cup as well?", "当然，您也需要一个杯子吗？"],
      ["Yes, and could you tell me what is in this meal?", "需要，还能告诉我这份餐食有哪些配料吗？"],
      ["I'll check the ingredient information for you.", "我会帮您查看配料信息。"],
      ["I missed the announcement about our connection.", "我没听清关于转机的广播。"],
      ["I'll repeat the information we have received.", "我来重复一下我们收到的信息。"],
    ] },
  ],
  "baggage-claim": [
    { title: "寻找行李转盘", roles: ["旅客", "工作人员"], lines: [
      ["Which carousel is handling bags from my flight?", "我的航班行李在哪个转盘领取？"],
      ["What flight number is printed on your boarding pass?", "您的登机牌上写着哪个航班号？"],
      ["It's AB twenty. I arrived from London.", "是AB二十次航班，我从伦敦来。"],
      ["Please check that flight on the baggage information screen.", "请在行李信息屏上查找这个航班。"],
      ["Where can I collect an oversized item?", "超大件行李在哪里领取？"],
      ["The oversized-baggage counter is beyond those carousels.", "超大件行李柜台在那些转盘后面。"],
    ] },
    { title: "报告行李未到", roles: ["旅客", "服务员"], lines: [
      ["The carousel has stopped, but my suitcase hasn't arrived.", "转盘停了，但我的行李箱还没到。"],
      ["Please show me your baggage tag and boarding pass.", "请出示您的行李标签和登机牌。"],
      ["It's a navy hard-shell case with a yellow ribbon.", "这是一个深蓝色硬壳箱，系着黄色丝带。"],
      ["Do you have a photograph of the case?", "您有这个箱子的照片吗？"],
      ["Yes. Could I have a reference number for this report?", "有，能给我这份报告的查询编号吗？"],
      ["Here it is. Keep it when you contact the baggage service.", "给您，联系行李服务部门时请留好它。"],
    ] },
  ],
  "airport-customs-hall": [
    { title: "确认入境通道", roles: ["旅客", "海关工作人员"], lines: [
      ["I am not sure which arrivals channel I should use.", "我不确定应该走哪条入境通道。"],
      ["Please read the current instructions before choosing a channel.", "请选择通道前请先阅读当前指引。"],
      ["I have an item that I need to declare.", "我有一件物品需要申报。"],
      ["Please use the channel marked for declarations and speak with an officer.", "请走标示为申报的通道，并与工作人员沟通。"],
      ["Could you tell me where to place this bag for inspection?", "能告诉我这只包要放在哪里检查吗？"],
      ["Set it on the tray and keep your documents with you.", "请把它放在托盘上，并随身保管好证件。"],
    ] },
    { title: "寻求协助与确认出口", roles: ["旅客", "海关工作人员"], lines: [
      ["I would like help understanding the declaration instructions.", "我需要帮助理解申报说明。"],
      ["I can direct you to the information desk for assistance.", "我可以指引您去服务台寻求帮助。"],
      ["May I keep this trolley with me while I ask?", "我询问时可以把行李车带在身边吗？"],
      ["Yes, keep it beside you and leave the lane clear.", "可以，请把行李车放在身边，不要挡住通道。"],
      ["Is the glass doorway the way out to arrivals?", "玻璃门那边是通往入境接机区的出口吗？"],
      ["Follow the public-arrivals signs beyond those doors.", "穿过那些门后，请跟随公共入境区的指示牌。"],
    ] },
  ],
  "airport-conveyor-drive-unit": [
    { title: "报告输送带卡阻", roles: ["地勤员工", "值班主管"], lines: [
      ["A suitcase has stopped beside the drive unit.", "一个行李箱停在驱动装置旁边。"],
      ["Please keep clear of the moving rollers.", "请与正在运转的滚筒保持距离。"],
      ["Should I reach in and move it?", "我可以伸手进去把它移开吗？"],
      ["No. Step back and notify the designated operator.", "不行。请退后并通知指定操作员。"],
      ["The lane is clear, and I have reported the jam.", "通道已经清空，我也报告了卡阻。"],
      ["Thanks. Wait here while the team follows the safe procedure.", "谢谢。请在这里等候，工作人员会按安全流程处理。"],
    ] },
    { title: "交接设备检查", roles: ["维修员", "值班主管"], lines: [
      ["The drive motor area is making an unusual noise.", "驱动电机区域有异常噪声。"],
      ["Has the conveyor been stopped and reported?", "输送带已经停机并报告了吗？"],
      ["Yes. I kept people clear and notified the supervisor.", "是的，我让人员避开并通知了主管。"],
      ["Please do not remove the guard or inspect inside the unit.", "请不要拆护罩，也不要检查装置内部。"],
      ["Understood. I will leave it to the authorized technician.", "明白，我会把它交给获授权的技术人员处理。"],
      ["I will record the location and wait for their instructions.", "我会记录位置并等待他们的指示。"],
    ] },
  ],
  "customs-baggage-examination": [
    { title: "配合行李检查", roles: ["旅客", "海关工作人员"], lines: [
      ["Where would you like me to place this carry-on?", "您希望我把这件随身行李放在哪里？"],
      ["Set it on the stainless inspection table, please.", "请把它放在不锈钢检查台上。"],
      ["Should I open the large compartment now?", "我现在要打开大隔层吗？"],
      ["Yes, open it when you are ready.", "是的，准备好时请打开。"],
      ["I packed some food in the side pocket. Should I declare it?", "我在侧袋里装了一些食物，需要申报吗？"],
      ["Please tell the officer what it is and follow the current declaration guidance.", "请告诉工作人员这是什么，并遵循当前申报指引。"],
    ] },
    { title: "整理物品与询问后续", roles: ["旅客", "海关工作人员"], lines: [
      ["Where should I keep my passport and travel papers?", "我的护照和旅行文件应该放在哪里？"],
      ["Please keep them with you while we examine the bag.", "检查行李时请随身保管这些文件。"],
      ["May I put my small belongings in this clean tray?", "我可以把小件物品放进这个干净托盘吗？"],
      ["Yes, use the empty tray beside the scale.", "可以，请使用秤旁边的空托盘。"],
      ["When can I repack my things?", "我什么时候可以重新整理行李？"],
      ["I will show you the packing space once we finish.", "检查结束后我会指给您整理行李的地方。"],
    ] },
  ],
  "library-reading-room": [
    { title: "找书与查目录", roles: ["读者", "馆员"], lines: [
      ["I'm looking for an introductory book about astronomy.", "我在找一本天文学入门书。"],
      ["Would you prefer an illustrated guide or a textbook?", "您更想要图解读物还是教材？"],
      ["An illustrated guide with a glossary would be helpful.", "带词汇表的图解读物会比较合适。"],
      ["Let's look up the title and shelf number in the catalogue.", "我们来目录中查找书名和书架编号。"],
      ["If it's on loan, can I reserve a copy?", "如果借出去了，我能预约一本吗？"],
      ["I can show you the reservation options for that title.", "我可以给您看这本书的预约选项。"],
    ] },
    { title: "借阅与安静学习", roles: ["读者", "馆员"], lines: [
      ["Where can I check the due date for these books?", "这些书的归还日期在哪里查看？"],
      ["You can find it on your loan receipt or library account.", "可以在借阅凭条或图书馆账户里查看。"],
      ["Is there a quiet desk with a power socket?", "有带电源插座的安静书桌吗？"],
      ["Try the desks along the wall in the reading room.", "可以去阅览室靠墙的书桌看看。"],
      ["May I leave my books here while I take a short break?", "我短暂休息时可以把书留在这里吗？"],
      ["Please check the desk-use notice and keep valuables with you.", "请查看书桌使用须知，并随身带好贵重物品。"],
    ] },
  ],
  "conference-room": [
    { title: "开始会议与共享屏幕", roles: ["主持人", "参会者"], lines: [
      ["Can everyone hear me clearly before we begin?", "开始前，大家都能听清我的声音吗？"],
      ["Your voice is clear, but we can't see your screen yet.", "声音很清楚，但我们还看不到您共享的屏幕。"],
      ["I'll share the agenda first, then open the proposal.", "我先共享议程，然后打开提案。"],
      ["Could you enlarge the figures on the second slide?", "能放大第二张幻灯片上的数字吗？"],
      ["Is this size readable from the back of the room?", "这个字号在会议室后排能看清吗？"],
      ["Yes. Please keep that view while we discuss the costs.", "可以，请保持这个画面，我们来讨论费用。"],
    ] },
    { title: "确认决定与分工", roles: ["主持人", "参会者"], lines: [
      ["What concerns do we need to resolve before agreeing?", "达成一致之前，我们需要解决哪些顾虑？"],
      ["We need to confirm the delivery date and available staff.", "我们需要确认交付日期和可用人员。"],
      ["Who will follow up with the supplier?", "谁来跟进供应商？"],
      ["I'll contact them and send an update tomorrow morning.", "我来联系他们，明早发送进展。"],
      ["Could you include the agreed actions in the minutes?", "能把商定的行动事项记入会议纪要吗？"],
      ["Yes, with an owner and a deadline for each action.", "可以，每项都会注明负责人和截止时间。"],
    ] },
  ],
  "school-catering-kitchen": [
    { title: "交接备餐任务", roles: ["同事甲", "同事乙"], lines: [
      ["Which preparation tasks are still outstanding?", "还有哪些备餐任务没完成？"],
      ["The vegetables are ready, but the serving trays need arranging.", "蔬菜准备好了，但还需要摆好供餐托盘。"],
      ["Where should I place the clean utensils?", "干净的用具应该放在哪里？"],
      ["Put them on the designated clean rack by the service pass.", "放在出餐口旁指定的清洁用具架上。"],
      ["Has the menu change been passed on to the serving team?", "菜单变动已经通知供餐团队了吗？"],
      ["Not yet. Please ask the supervisor to confirm it with them.", "还没有，请主管和他们确认一下。"],
    ] },
    { title: "确认标签与报告问题", roles: ["同事甲", "主管"], lines: [
      ["The label on this container is difficult to read.", "这个容器上的标签不太清楚。"],
      ["Set it aside while we check the preparation record.", "先把它放在一旁，我们查一下制备记录。"],
      ["A student has asked about allergens in today's dish.", "有学生问今天这道菜含有哪些过敏原。"],
      ["Please use the approved ingredient information, not a guess.", "请查看已确认的配料信息，不要猜测。"],
      ["There is also a loose handle on the trolley.", "另外，推车上有一个把手松了。"],
      ["Leave that trolley out of use and report it for repair.", "先停用那辆推车，并报修。"],
    ] },
  ],
  "school-dining-hall": [
    { title: "选餐与份量", roles: ["学生", "供餐员"], lines: [
      ["Could I have rice with vegetables, please?", "请给我米饭配蔬菜。"],
      ["Would you like a small portion or a regular portion?", "你要小份还是普通份？"],
      ["A small portion, and some soup on the side.", "小份，再单独来些汤。"],
      ["Take a bowl from the shelf beside the trays.", "从托盘旁的架子上拿一个碗。"],
      ["Is drinking water included?", "包含饮用水吗？"],
      ["Yes. The water dispenser is beside the cups.", "包含，饮水机就在杯子旁边。"],
    ] },
    { title: "找座位与收餐盘", roles: ["新同学", "同学"], lines: [
      ["Is this seat taken?", "这个座位有人吗？"],
      ["No, you can put your tray here.", "没有，你可以把托盘放这里。"],
      ["Where do we take our plates afterwards?", "吃完后盘子放到哪里？"],
      ["Put them on the return counter near the exit.", "放在出口附近的回收台上。"],
      ["Do we separate the food scraps?", "剩饭需要分开倒吗？"],
      ["Yes, empty them into the food-waste bin first.", "需要，先倒进厨余垃圾桶。"],
    ] },
  ],
  "city-cafe": [
    { title: "点咖啡与打包", roles: ["顾客", "店员"], lines: [
      ["I'd like a medium latte with oat milk.", "我想要一杯中杯燕麦奶拿铁。"],
      ["Would you like it hot or iced?", "你要热的还是冰的？"],
      ["Iced, with less ice, please.", "冰的，请少放冰。"],
      ["Will that be for here or to go?", "在这里喝还是带走？"],
      ["To go. Could I have a lid, please?", "带走，请给我一个杯盖。"],
      ["Of course. Please collect your drink at the counter.", "当然，请在柜台取饮品。"],
    ] },
    { title: "确认订单与付款", roles: ["顾客", "店员"], lines: [
      ["I ordered a decaf coffee. Is this mine?", "我点了低因咖啡，这是我的吗？"],
      ["Let me check your order number.", "让我核对一下你的订单号。"],
      ["It's twenty-three. I also ordered a sandwich.", "是二十三号，我还点了一份三明治。"],
      ["Your sandwich is ready. Would you like it heated?", "三明治好了，需要加热吗？"],
      ["Yes, please. Can I pay by card?", "需要，谢谢。我可以刷卡吗？"],
      ["Yes. Tap your card here and take your receipt.", "可以，在这里感应卡片，然后拿好收据。"],
    ] },
  ],
  airport: [
    { title: "办理值机", roles: ["旅客", "值机员"], lines: [
      ["I'd like to check in for my flight to London.", "我想办理飞往伦敦的航班值机。"],
      ["May I see your passport and booking reference?", "请出示护照和预订编号。"],
      ["Here they are. Could I have an aisle seat?", "给您。我可以选靠过道的座位吗？"],
      ["Yes. How many bags are you checking in?", "可以。您要托运几件行李？"],
      ["One suitcase. This backpack is my carry-on.", "一个行李箱。这个背包是随身行李。"],
      ["Please place the suitcase on the scale.", "请把行李箱放到秤上。"],
    ] },
    { title: "确认登机口", roles: ["旅客", "工作人员"], lines: [
      ["Has the gate for flight AB twenty changed?", "AB二十次航班的登机口变了吗？"],
      ["Yes, it is now gate twelve in terminal two.", "变了，现在是二号航站楼十二号登机口。"],
      ["How do I get there from here?", "从这里怎么过去？"],
      ["Follow the signs and take the shuttle downstairs.", "沿着指示牌走，到楼下乘接驳车。"],
      ["Has boarding started yet?", "已经开始登机了吗？"],
      ["Not yet. Check the departure screen for updates.", "还没有，请看出发信息屏上的更新。"],
    ] },
  ],
  hospital: [
    { title: "挂号与问路", roles: ["来访者", "接待员"], lines: [
      ["I have an appointment at ten thirty.", "我预约了十点半。"],
      ["What is your name, please?", "请问您叫什么名字？"],
      ["Alex Chen. Where should I check in?", "陈Alex。我应该在哪里登记？"],
      ["Please check in at the reception desk on this floor.", "请在本层的接待台登记。"],
      ["Is there a lift to the outpatient clinic?", "有电梯可以到门诊吗？"],
      ["Yes, the lifts are past the waiting area.", "有，穿过候诊区就是电梯。"],
    ] },
    { title: "说明情况与沟通需求", roles: ["患者", "工作人员"], lines: [
      ["I'd like to describe my symptoms to the doctor.", "我想向医生说明我的症状。"],
      ["Please tell the doctor when they started.", "请告诉医生症状是什么时候开始的。"],
      ["Could I have an interpreter for the appointment?", "就诊时可以安排口译员吗？"],
      ["Which language would you prefer?", "您希望使用哪种语言？"],
      ["Mandarin, please. Could you write the instructions down?", "普通话，谢谢。您能把说明写下来吗？"],
      ["I will ask the clinical team to help you.", "我会请医护团队帮助您。"],
    ] },
  ],
  "school-locker-bank": [
    { title: "询问密码锁与卡住的柜门", roles: ["学生", "学校工作人员"], lines: [
      ["I can't open my locker after entering the combination.", "输入密码后，我还是打不开储物柜。"],
      ["Which locker are you trying to open?", "你想打开的是哪个储物柜？"],
      ["The blue door beside the open locker.", "旁边那扇蓝色的柜门，就在敞开的柜子旁。"],
      ["Please don't force the door or twist the handle.", "请不要硬拉柜门，也不要扭动把手。"],
      ["Could you check the dial and latch for me?", "你能帮我检查一下转盘和锁扣吗？"],
      ["I'll ask the school office to check the jammed lock.", "我会请学校办公室检查卡住的锁。"],
    ] },
    { title: "存放物品与归还失物", roles: ["学生", "学校工作人员"], lines: [
      ["I left my water bottle on the bench.", "我把水瓶落在长椅上了。"],
      ["Is it the clear bottle beside the dark backpack?", "是深色背包旁边的透明水瓶吗？"],
      ["Yes, and my lunch box is beside it too.", "是的，我的午餐盒也在旁边。"],
      ["I found a pair of shoes inside the open locker.", "我在敞开的储物柜里发现了一双鞋。"],
      ["They aren't mine. Should I take them to the office?", "不是我的。我应该把它们交到办公室吗？"],
      ["Yes, please hand in anything you find.", "是的，请把捡到的物品交到办公室。"],
    ] },
  ],
  "hospital-pharmacy": [
    { title: "领取处方药", roles: ["患者", "药师"], lines: [
      ["I'm here to collect my prescription.", "我来领取处方药。"],
      ["Please confirm your name and date of birth.", "请确认您的姓名和出生日期。"],
      ["Could you explain the label to me?", "您能为我解释药品标签吗？"],
      ["Let's go through the instructions together.", "我们一起逐条看一下说明。"],
      ["Could you write down how I should store it?", "您能写下应该如何保存吗？"],
      ["Yes. Please ask if any part is unclear.", "可以，有不清楚的地方请问我。"],
    ] },
    { title: "向药师确认用药疑问", roles: ["患者", "药师"], lines: [
      ["I take another medicine. Can you check for interactions?", "我还在用另一种药，您能检查是否有相互作用吗？"],
      ["Please show me the names of everything you take.", "请给我看看您使用的所有药品名称。"],
      ["Should I mention supplements as well?", "也需要说明补充剂吗？"],
      ["Yes, please include those in the list.", "需要，请一并列出来。"],
      ["Who should I contact if I have more questions?", "如果还有疑问，我应该联系谁？"],
      ["You can contact the pharmacy or your prescriber.", "您可以联系药房或开处方的医护人员。"],
    ] },
    { title: "核对不同名称的药品", roles: ["患者", "药师"], lines: [
      ["The name on this box looks different from my previous supply.", "这盒药上的名称和我上次领到的看起来不一样。"],
      ["Let's compare the label with your prescription.", "我们一起对照标签和您的处方。"],
      ["Could this be a generic medicine?", "这可能是通用名药品吗？"],
      ["I'll check the active ingredient and confirm the product.", "我会核对有效成分并确认具体药品。"],
      ["Should I use it before the label has been checked?", "标签还没核对清楚前，我应该先使用它吗？"],
      ["Please wait while I verify the instructions.", "请稍等，我先核实使用说明。"],
    ] },
  ],
  "office-building": [
    { title: "访客登记", roles: ["访客", "前台"], lines: [
      ["I'm here for a meeting with Jordan Lee.", "我来与Jordan Lee开会。"],
      ["Which company are you visiting?", "您要拜访哪家公司？"],
      ["North Studio on the fifth floor.", "五楼的North Studio。"],
      ["Please sign in and wear this visitor badge.", "请登记，并佩戴这张访客证。"],
      ["Do I need an access card for the lift?", "乘电梯需要门禁卡吗？"],
      ["Your host will meet you here and take you upstairs.", "接待您的人会来这里带您上楼。"],
    ] },
    { title: "会议室与设备", roles: ["同事甲", "同事乙"], lines: [
      ["Is this meeting room available until noon?", "这间会议室到中午之前有空吗？"],
      ["Yes, but please reserve it on the booking system.", "有，不过请先在预订系统中预约。"],
      ["Where can I connect my laptop to the screen?", "我在哪里可以把笔记本接到屏幕上？"],
      ["There is an HDMI cable in the centre of the table.", "桌子中央有一根HDMI线。"],
      ["Could you lower the blinds before we start?", "开始前你能把百叶窗放下来吗？"],
      ["Sure. I'll also check the microphone.", "可以，我也检查一下麦克风。"],
    ] },
  ],
  "office-reception-lobby": [
    { title: "到访登记与联系接待人", roles: ["访客", "接待员"], lines: [
      ["I am expected for a meeting, but I do not see my host.", "我约了开会，但还没有看到接待我的人。"],
      ["Please tell me their name and the company you are visiting.", "请告诉我对方姓名和您要拜访的公司。"],
      ["I have checked in. Where should I wait?", "我已经登记了，应该在哪里等候？"],
      ["Please take a seat in the waiting area beside the lobby.", "请在大厅旁边的等候区就座。"],
      ["Should I return this visitor badge when I leave?", "离开时需要归还这张访客证吗？"],
      ["Yes, please hand it to reception before you exit.", "需要，请在离开前把它交还给前台。"],
    ] },
    { title: "确认门禁与电梯路线", roles: ["访客", "接待员"], lines: [
      ["The access gate did not open when I presented my badge.", "我刷访客证后，门禁闸机没有打开。"],
      ["Please come back to reception so I can check the access arrangement.", "请回到前台，我来核对门禁安排。"],
      ["Can I use the passenger lift to reach the meeting floor?", "我可以乘客用电梯去会议所在楼层吗？"],
      ["Yes. Your host can confirm the floor and accompany you there.", "可以，具体楼层请由您的接待人确认并陪同您前往。"],
      ["Where can I place my umbrella while I wait?", "等候时我可以把雨伞放在哪里？"],
      ["There is an umbrella stand beside the lobby coat rack.", "大厅衣帽架旁边有雨伞架。"],
    ] },
  ],
  "emergency-department": [
    { title: "说明情况并登记", roles: ["来访者", "分诊护士"], lines: [
      ["I feel unwell and need some help.", "我感觉不舒服，需要帮助。"],
      ["What would you like the care team to know?", "您希望医护团队了解什么情况？"],
      ["The pain started this morning.", "疼痛是今天早上开始的。"],
      ["Is anyone here with you?", "有人陪您一起来吗？"],
      ["My sister is waiting near the entrance.", "我姐姐在入口附近等我。"],
      ["I'll let the care team know.", "我会通知医护团队。"],
    ] },
    { title: "确认候诊安排", roles: ["患者", "接待员"], lines: [
      ["Where should I wait after checking in?", "登记后我应该在哪里等候？"],
      ["Please take a seat by the blue wall.", "请在蓝色墙边坐下等候。"],
      ["How will I know when it's my turn?", "我怎么知道什么时候轮到我？"],
      ["A staff member will call your name.", "工作人员会叫您的名字。"],
      ["Could you say it slowly so I can hear clearly?", "您能慢一点说吗？这样我能听清楚。"],
      ["Of course. Tell the desk if you need any help.", "当然。如果需要帮助，请告诉服务台。"],
    ] },
    { title: "说明用药与语言需求", roles: ["患者", "分诊护士"], lines: [
      ["I brought a list of my medicines and allergies.", "我带来了用药和过敏情况清单。"],
      ["Thank you. Please show it to the triage nurse.", "谢谢，请把它交给分诊护士查看。"],
      ["I feel more comfortable speaking Mandarin.", "我用普通话交流会更自在。"],
      ["Would you like help requesting an interpreter?", "您需要我们帮忙申请口译员吗？"],
      ["Yes, and I would like to explain when this started.", "需要，我还想说明这种情况是什么时候开始的。"],
      ["I'll let the care team know what support you requested.", "我会把您需要的协助告知医护团队。"],
    ] },
  ],
  "emergency-triage-reception": [
    { title: "办理登记并说明来意", roles: ["患者", "接待员"], lines: [
      ["I would like to check in and speak with the triage nurse.", "我想办理登记，并和分诊护士谈一谈。"],
      ["Please tell me what brought you to the emergency department.", "请告诉我您因为什么来到急诊科。"],
      ["I have a symptom that began this morning.", "我有一种今天早上开始出现的症状。"],
      ["When did you first notice it?", "您最初是什么时候注意到的？"],
      ["I wrote down a few details to help me explain.", "我记下了一些细节，方便说明情况。"],
      ["Thank you. I will pass that information to the clinical team.", "谢谢，我会把这些信息转告给医护团队。"],
    ] },
    { title: "请求口译和沟通协助", roles: ["患者", "分诊护士"], lines: [
      ["I would feel more comfortable speaking Mandarin.", "用普通话交流会让我感觉更自在。"],
      ["Could you arrange a Mandarin interpreter to join our conversation?", "您能安排一位普通话口译员来协助交流吗？"],
      ["Yes, please. I want to describe what has changed.", "需要，谢谢。我想说明情况有哪些变化。"],
      ["I will check what language support is available.", "我会确认目前有哪些语言协助服务。"],
      ["Could I show you the notes I brought with me?", "我可以给您看我带来的记录吗？"],
      ["Yes. Please show them to the triage nurse.", "可以，请把记录给分诊护士看。"],
    ] },
    { title: "确认候诊位置并及时求助", roles: ["患者", "接待员"], lines: [
      ["Where should I wait after I have checked in?", "登记后我应该在哪里等候？"],
      ["Please take a seat in the waiting area.", "请在候诊区找个座位坐下。"],
      ["What should I do if I start to feel worse?", "如果我开始感觉更不舒服，应该怎么办？"],
      ["Please tell a member of staff straight away.", "请马上告诉工作人员。"],
      ["May I keep the wheelchair beside me while I wait?", "等候时我可以把轮椅放在身边吗？"],
      ["Yes. Let us know if you need help moving it.", "可以。如果移动时需要帮助，请告诉我们。"],
    ] },
  ],
  "emergency-assessment-bay": [
    { title: "描述不适与变化", roles: ["患者", "护士"], lines: [
      ["The discomfort is on my left side.", "不适在我的左侧。"],
      ["When did the discomfort first begin?", "这种不适最初是什么时候开始的？"],
      ["It began about an hour ago.", "大约一小时前开始的。"],
      ["Has anything changed since then?", "从那时起有什么变化吗？"],
      ["It feels worse when I move.", "我活动时感觉更不舒服。"],
      ["Please let us know if it changes while we assess you.", "评估期间如果情况有变化，请告诉我们。"],
    ] },
    { title: "了解检查与设备", roles: ["患者", "护士"], lines: [
      ["Could you explain what the monitor is for?", "您能解释一下这台监护仪的用途吗？"],
      ["It helps the care team check you during your assessment.", "它可以帮助医护团队在评估期间查看您的情况。"],
      ["Will you explain before carrying out a check?", "进行检查前，您会先向我说明吗？"],
      ["Yes. I will explain each step and answer your questions.", "会的，我会说明每一步并回答您的问题。"],
      ["May I ask you to pause if I feel uncomfortable?", "如果我感觉不舒服，可以请您暂停吗？"],
      ["Yes. Please tell me, and we can talk about it.", "可以，请告诉我，我们可以先沟通一下。"],
    ] },
    { title: "请求口译与维护隐私", roles: ["患者", "护士"], lines: [
      ["Could I speak with an interpreter?", "我可以请口译员协助交流吗？"],
      ["I can ask the team to arrange language support.", "我可以请团队安排语言协助。"],
      ["Could you close the curtain while we talk?", "我们交谈时，您能拉上隔帘吗？"],
      ["Of course. I will give you as much privacy as possible.", "当然，我会尽可能保护您的隐私。"],
      ["Where should I put my belongings?", "我的随身物品应该放在哪里？"],
      ["Keep them with you, and tell us if you need help.", "请把物品放在身边；如果需要帮助，请告诉我们。"],
    ] },
  ],
  "hospital-inpatient-bedspace": [
    { title: "询问床旁设备与呼叫方式", roles: ["患者", "护士"], lines: [
      ["Could you show me how to use the nurse-call handset?", "您能教我怎样使用护士呼叫器吗？"],
      ["Press this button if you need assistance from the care team.", "需要医护人员协助时，请按这个按钮。"],
      ["Is the water jug on this table for me?", "桌上的水壶是给我用的吗？"],
      ["Yes, and please tell us if you need help reaching it.", "是的，如果您拿取不方便，请告诉我们。"],
      ["Could you move the visitor chair closer to the bed?", "能把访客椅移到离床近一些的位置吗？"],
      ["Certainly. I will keep the walkway clear as I move it.", "当然，我移动时会注意保持通道畅通。"],
    ] },
    { title: "说明沟通与个人物品需求", roles: ["患者", "病房工作人员"], lines: [
      ["I find it easier to understand written instructions.", "我看书面说明会更容易理解。"],
      ["I can ask the team to provide the information in writing.", "我可以请团队提供书面信息。"],
      ["Where should I keep my glasses and phone?", "我的眼镜和手机应该放在哪里？"],
      ["You can use the bedside cabinet, and keep valuables with you.", "您可以使用床旁柜，贵重物品请随身保管。"],
      ["Could you explain the call bell again, more slowly?", "能再慢一点解释一下呼叫铃的用法吗？"],
      ["Of course. I will show you the button and wait while you try it.", "当然，我会指给您看按钮，并等您试着操作。"],
    ] },
    { title: "确认出院后的沟通", roles: ["患者", "护士"], lines: [
      ["Could you explain the plan for going home?", "您能说明一下回家前的安排吗？"],
      ["The clinical team will review the plan with you.", "医护团队会和您一起确认安排。"],
      ["Could I have the instructions in writing?", "能给我一份书面说明吗？"],
      ["Yes. I'll ask the team to provide a copy.", "可以，我会请团队提供一份。"],
      ["Who should I contact if I have a question later?", "之后有问题时，我应该联系谁？"],
      ["Please check the contact details on your discharge papers.", "请查看出院文件上的联系信息。"],
    ] },
  ],
  "intensive-care-unit": [
    { title: "了解探访安排", roles: ["家属", "护士"], lines: [
      ["May I visit my father now?", "我现在可以探望父亲吗？"],
      ["Please check in at the nurses' station first.", "请先到护士站登记。"],
      ["Do I need to wear a visitor badge?", "我需要佩戴访客证吗？"],
      ["Yes, please wear it while you're in the unit.", "需要，请在病区内佩戴。"],
      ["Can I leave him this card?", "我可以把这张卡片留给他吗？"],
      ["Please ask his nurse before leaving it.", "留下之前请先问负责他的护士。"],
    ] },
    { title: "询问下一步与求助", roles: ["家属", "护士"], lines: [
      ["When do visiting hours end today?", "今天的探访时间几点结束？"],
      ["The schedule is posted beside the door.", "时间安排贴在门旁边。"],
      ["I have a question about the notice on the door.", "我想问一下门上的告示。"],
      ["Which part would you like me to explain?", "您想让我解释哪一部分？"],
      ["It says to clean my hands before entering.", "上面写着进入前要清洁双手。"],
      ["Please use the hand rub beside the entrance.", "请使用入口旁的免洗手消毒液。"],
    ] },
    { title: "询问床旁监护设备", roles: ["家属", "护士"], lines: [
      ["The monitor is beeping. Should I press a button?", "监护仪在响，我需要按哪个按钮吗？"],
      ["Please do not touch it; use the call button to reach us.", "请不要触碰设备；按呼叫按钮联系工作人员。"],
      ["Could you explain what the alarm means?", "您能解释一下这个警报是什么意思吗？"],
      ["I'll check with the care team and explain what I can.", "我会向医护团队确认，再为您说明我能解释的部分。"],
      ["Should I clean my hands before going to the bedside?", "到床旁前我需要清洁双手吗？"],
      ["Yes. Please use the hand rub at the unit entrance.", "需要，请使用病区入口处的免洗手消毒液。"],
    ] },
  ],
  "operating-theatre": [
    { title: "找到术前等候区", roles: ["患者", "工作人员"], lines: [
      ["Where should I leave my coat and bag?", "我的外套和包应该放在哪里？"],
      ["You can use the lockers beside the changing area.", "您可以使用更衣区旁的储物柜。"],
      ["Is this the entrance to the pre-op area?", "这里是术前准备区的入口吗？"],
      ["Yes. Please wait until a staff member invites you in.", "是的，请等工作人员邀请您进入。"],
      ["My appointment is under the name Chen.", "我的预约登记在陈这个姓氏下。"],
      ["Please confirm your full name at the check-in desk.", "请在登记台确认您的全名。"],
    ] },
    { title: "请求解释与语言协助", roles: ["患者", "护士"], lines: [
      ["Could you explain what happens next?", "您能解释一下接下来会怎样吗？"],
      ["The care team will explain each step to you.", "医护团队会向您逐步说明。"],
      ["Would you write the main points down for me?", "您能把主要内容写下来吗？"],
      ["Certainly. I can also arrange an interpreter.", "当然。我也可以为您安排口译员。"],
      ["Thank you. I need a moment to read this.", "谢谢，我需要一点时间读一下。"],
      ["Take your time and ask if anything is unclear.", "请慢慢看，有不清楚的地方就问我。"],
    ] },
    { title: "补充过敏与知情沟通", roles: ["患者", "护士"], lines: [
      ["I need to add a medicine allergy to my record.", "我需要在记录里补充一项药物过敏。"],
      ["Please tell the surgical team before the procedure begins.", "请在手术开始前告知手术团队。"],
      ["Could you go through the consent form with me?", "您能和我一起看一下知情同意书吗？"],
      ["The team can pause and answer questions before you decide.", "您作决定前，团队可以停下来回答您的问题。"],
      ["I need an interpreter before I sign anything.", "签署任何文件前，我需要口译员协助。"],
      ["I'll arrange language support and let the team know.", "我会安排语言协助并通知团队。"],
    ] },
  ],
  "radiology-suite": [
    { title: "找到影像检查室", roles: ["患者", "工作人员"], lines: [
      ["I've come for an imaging appointment. Where do I check in?", "我来做影像检查，应该在哪里登记？"],
      ["Please show your appointment letter at this desk.", "请在这个服务台出示预约单。"],
      ["Is there a place to store my bag?", "有地方可以存放我的包吗？"],
      ["The lockers are beside the changing rooms.", "储物柜在更衣室旁边。"],
      ["Should I keep this form with me?", "这张表格需要我随身带着吗？"],
      ["Please give it to the staff member when your name is called.", "工作人员叫到您时，请把表格交给他们。"],
    ] },
    { title: "确认等候地点与协助", roles: ["患者", "工作人员"], lines: [
      ["How do I get to the ultrasound rooms?", "超声检查室怎么走？"],
      ["Walk past reception and turn left at the lift.", "经过接待处，在电梯旁左转。"],
      ["My appointment letter says room four.", "我的预约单上写着四号房间。"],
      ["Please check in here before going through that door.", "经过那扇门之前，请先在这里登记。"],
      ["Could someone help me with a wheelchair?", "有人能帮我安排轮椅吗？"],
      ["I'll contact the support team for you.", "我来帮您联系协助团队。"],
    ] },
    { title: "告知影像检查相关信息", roles: ["患者", "放射技师"], lines: [
      ["I may be pregnant. Should I tell the radiographer?", "我可能怀孕了，需要告诉放射技师吗？"],
      ["Yes. Please tell the radiology team before the examination.", "需要，请在检查前告知放射科团队。"],
      ["I also have a metal implant.", "我体内还有一个金属植入物。"],
      ["Please share that so the team can check the details.", "请告知团队，以便他们核对具体情况。"],
      ["Will I receive the scan results here?", "我会在这里拿到影像检查结果吗？"],
      ["The clinician who requested it can explain how results are shared.", "开具检查的临床医生可以说明结果会如何告知。"],
    ] },
  ],
  "pathology-lab": [
    { title: "核对样本标签", roles: ["实验室同事甲", "实验室同事乙"], lines: [
      ["The sample label doesn't match the request form.", "样本标签和申请单对不上。"],
      ["Please place both items in the review tray.", "请把两样东西都放进复核托盘。"],
      ["Should I replace the label now?", "我现在要换掉这个标签吗？"],
      ["Wait until the supervisor checks the record.", "等主管核对记录后再处理。"],
      ["I've added a note to the batch log.", "我已经在批次记录里加了备注。"],
      ["Thanks. Keep the sample in its assigned rack.", "谢谢，把样本放回指定的架子上。"],
    ] },
    { title: "整理切片与报告问题", roles: ["技术员", "主管"], lines: [
      ["Could you bring the stained slides to bench three?", "能把染色切片拿到三号工作台吗？"],
      ["They're in the covered tray beside the microscope.", "它们在显微镜旁边的带盖托盘里。"],
      ["Which case number should I record?", "我应该记录哪个病例编号？"],
      ["Use the number printed on each slide label.", "请使用每张切片标签上印的编号。"],
      ["This slide has no label.", "这张切片没有标签。"],
      ["Set it aside and report it to the supervisor.", "先把它放在一旁，并报告给主管。"],
    ] },
    { title: "确认病理报告的沟通", roles: ["实验室技术员", "临床医生"], lines: [
      ["The biopsy specimen is ready for review.", "活检标本已准备好复核。"],
      ["Please confirm the patient identifiers against the request.", "请对照申请单核实患者身份信息。"],
      ["The report uses the term carcinoma.", "报告中使用了 carcinoma（癌）这个术语。"],
      ["The treating clinician should explain what the finding means.", "检查结果的含义应由负责治疗的临床医生解释。"],
      ["Where should I record the case number?", "我应该在哪里记录病例编号？"],
      ["Use the approved laboratory record for this case.", "请在该病例的正式实验室记录中登记。"],
    ] },
  ],
  "check-in-counter": [
    { title: "申请登机协助", roles: ["旅客", "值机员"], lines: [
      ["I'd like some extra time when boarding begins.", "我希望登机时能多一些时间。"],
      ["What kind of assistance would be helpful?", "什么样的协助对您有帮助？"],
      ["I need a seat while I wait near the gate.", "我在登机口附近等候时需要座位。"],
      ["I'll add a note to your booking.", "我会在您的预订里添加备注。"],
      ["Where should I ask for help later?", "之后我应该在哪里寻求帮助？"],
      ["Please speak to the airport team at your gate.", "请向登机口的机场工作人员咨询。"],
    ] },
    { title: "确认行程信息", roles: ["旅客", "值机员"], lines: [
      ["My phone number has changed since I booked.", "预订之后我的电话号码变了。"],
      ["I can update the contact details on your booking.", "我可以更新您预订中的联系方式。"],
      ["Does my flight still leave at six?", "我的航班还是六点起飞吗？"],
      ["Let me check the latest departure information.", "我来查看最新的出发信息。"],
      ["Could you print the updated itinerary?", "您能打印更新后的行程单吗？"],
      ["Of course. Please check the details before you leave.", "当然，请在离开前核对一下信息。"],
    ] },
  ],
  "baggage-drop-station": [
    { title: "核对行李标签", roles: ["旅客", "工作人员"], lines: [
      ["This tag shows flight AB twenty.", "这个行李标签上写着AB二十次航班。"],
      ["Please check that the destination code is correct.", "请核对目的地代码是否正确。"],
      ["It should say SYD. Can you verify it?", "应该写SYD。您能帮我确认吗？"],
      ["Yes, this label is for Sydney.", "是的，这个标签的目的地是悉尼。"],
      ["Where should I leave the suitcase?", "我应该把行李箱放在哪里？"],
      ["Place it on the marked belt after the light turns green.", "指示灯变绿后，把它放到标记的传送带上。"],
    ] },
    { title: "询问特殊行李", roles: ["旅客", "工作人员"], lines: [
      ["This case has a musical instrument inside.", "这个箱子里装着一件乐器。"],
      ["Please ask the airline team about the handling options.", "请向航空公司工作人员询问处理方式。"],
      ["Can I carry the small case with me?", "这个小箱子我可以随身带着吗？"],
      ["They can check the size and explain the current rules.", "他们可以测量尺寸并说明当前规定。"],
      ["Where is the service desk?", "服务台在哪里？"],
      ["It's beside the oversized-baggage sign.", "它在超大行李标志旁边。"],
    ] },
  ],
  "boarding-gate": [
    { title: "确认登机口与广播", roles: ["旅客", "工作人员"], lines: [
      ["My pass says gate twelve. Is that still correct?", "我的登机牌写着十二号登机口，现在还是吗？"],
      ["The screen now shows gate fourteen.", "屏幕现在显示十四号登机口。"],
      ["How long does it take to walk there?", "走到那里要多久？"],
      ["It's about five minutes from here.", "从这里走过去大约需要五分钟。"],
      ["Have they called my group yet?", "他们已经叫到我的组别了吗？"],
      ["Not yet. Please wait until your group is called.", "还没有，请等候工作人员叫到您的组别。"],
    ] },
    { title: "询问登机顺序", roles: ["旅客", "工作人员"], lines: [
      ["Can I board with my family?", "我能和家人一起登机吗？"],
      ["Please check the group number on each boarding pass.", "请查看每张登机牌上的组别号码。"],
      ["Mine says group three.", "我的登机牌上写着三组。"],
      ["We'll call each group when it's ready to board.", "轮到登机时，我们会叫到每个组别。"],
      ["Is there a lift to the boarding lane?", "去登机通道有电梯吗？"],
      ["Follow the signs to the accessible boarding lane.", "沿着标志走到无障碍登机通道。"],
    ] },
  ],
  "passenger-boarding-bridge": [
    { title: "穿过登机廊桥", roles: ["旅客", "工作人员"], lines: [
      ["Is this the walkway to the aircraft?", "这是通往飞机的通道吗？"],
      ["Yes. Follow the enclosed bridge to the cabin doorway.", "是的，沿着封闭廊桥走到客舱门口。"],
      ["Could I hold the handrail while I cross?", "我可以扶着扶手通过吗？"],
      ["Of course. Please keep the boarding path clear.", "当然，请保持登机通道畅通。"],
      ["Where can I speak to a staff member?", "我可以在哪里联系工作人员？"],
      ["Use the emergency phone beside the bridge controls.", "请使用廊桥控制装置旁的应急电话。"],
    ] },
    { title: "确认登机协助", roles: ["旅客", "工作人员"], lines: [
      ["I requested boarding assistance with my booking.", "我在预订时申请了登机协助。"],
      ["Please tell the gate team before you continue.", "继续登机前请告知登机口工作人员。"],
      ["Is the aircraft doorway at the end of this bridge?", "飞机舱门在这座廊桥的尽头吗？"],
      ["Yes. The cabin entrance is directly ahead.", "是的，客舱入口就在前方。"],
      ["Should I touch the bridge control panel?", "我需要操作廊桥控制面板吗？"],
      ["No. Only authorised airport staff operate that equipment.", "不用，只有获授权的机场工作人员才能操作该设备。"],
    ] },
  ],
  "office-elevator-car": [
    { title: "选择楼层与进出电梯", roles: ["访客", "同事"], lines: [
      ["Which button should I press for level five?", "去五楼应该按哪个按钮？"],
      ["Choose the floor button for your destination.", "请选择你要去的楼层按钮。"],
      ["Could you hold the door while I enter?", "我进来时你能帮我挡一下门吗？"],
      ["Please keep clear of the closing doors.", "请避开正在关闭的电梯门。"],
      ["Is there enough room for a wheelchair?", "轿厢里有足够的轮椅空间吗？"],
      ["There is an open area between the side handrails.", "两侧扶手之间有一片空地。"],
    ] },
    { title: "使用轿厢控制与寻求帮助", roles: ["访客", "同事"], lines: [
      ["Could you show me the door-open control?", "你能指给我看开门按钮吗？"],
      ["It is on the car panel beside the other buttons.", "它在轿厢面板上，和其他按钮在一起。"],
      ["What should I do if I need assistance?", "如果我需要帮助，应该怎么做？"],
      ["Use the assistance control and follow the building guidance.", "请使用求助按钮并遵循大楼指引。"],
      ["Can I see the floor indicator from here?", "我在这里能看到楼层显示窗吗？"],
      ["Yes, look above the control panel.", "能，请看控制面板上方。"],
    ] },
  ],
  "open-plan-workstation": [
    { title: "使用共享工位", roles: ["新同事", "同事"], lines: [
      ["Is this desk free for today?", "这张桌子今天可以用吗？"],
      ["Yes, but please book it in the shared calendar.", "可以，不过请在共享日历里预订。"],
      ["Where can I find a monitor cable?", "我在哪里能找到显示器连接线？"],
      ["There's a spare one in the equipment drawer.", "设备抽屉里有一根备用的。"],
      ["May I borrow this headset?", "我可以借用这个耳机吗？"],
      ["Sure. Please return it before you leave.", "当然，请在离开前归还。"],
    ] },
    { title: "一起检查工作文件", roles: ["同事甲", "同事乙"], lines: [
      ["Could we review the draft together?", "我们可以一起检查这份草稿吗？"],
      ["Sure. Shall we use the small meeting booth?", "可以。我们用那个小会议间好吗？"],
      ["I need the latest version of the file.", "我需要这份文件的最新版。"],
      ["It's in the project folder under today's date.", "它在项目文件夹今天日期的目录里。"],
      ["Could you point out the changes?", "您能指出修改的地方吗？"],
      ["Look at the notes in the right-hand column.", "请看右侧那一栏的备注。"],
    ] },
  ],
  "office-network-rack": [
    { title: "追踪机柜跳线", roles: ["同事", "IT技术员"], lines: [
      ["Could you help me trace this patch cable?", "你能帮我追踪这根跳线吗？"],
      ["Let's check the rack and port labels first.", "我们先核对机柜和端口标签。"],
      ["This cable runs from the patch panel to the switch.", "这根线从配线架连到交换机。"],
      ["Does the label match the change request?", "标签和变更申请一致吗？"],
      ["Yes, but I will wait for approval before moving it.", "一致，但我会等批准后再移动它。"],
      ["Good. Record the port mapping after the approved change.", "好，获批变更后请记录端口对应关系。"],
    ] },
    { title: "报告机柜布线问题", roles: ["同事", "IT技术员"], lines: [
      ["One cable is blocking the rack's front airflow path.", "有一根线挡住了机柜前方的气流通道。"],
      ["Are you sure which device it connects to?", "你确定它连接的是哪台设备吗？"],
      ["No, so I have not unplugged or moved it.", "不确定，所以我没有拔掉或移动它。"],
      ["Please check the port record and contact the device owner.", "请核对端口记录并联系设备负责人。"],
      ["I found the owner and opened a change request.", "我找到负责人并提交了变更申请。"],
      ["Thanks. We can reroute it during the approved maintenance window.", "谢谢。我们可以在获批的维护窗口重新布线。"],
    ] },
  ],
  "service-core": [
    { title: "报告设施故障", roles: ["员工", "设施人员"], lines: [
      ["The corridor light is flickering.", "走廊里的灯在闪。"],
      ["Thanks. I'll log a maintenance request.", "谢谢，我会登记维修申请。"],
      ["It's outside room 5B, beside the service door.", "它在5B房间外，服务门旁边。"],
      ["Could you keep the area clear while we check?", "检查期间可以先保持这块区域畅通吗？"],
      ["Can I use the other corridor?", "我可以走另一条走廊吗？"],
      ["Yes. Follow the signs to the north lift.", "可以，沿着标志走到北侧电梯。"],
    ] },
    { title: "问路并跟进维修", roles: ["访客", "设施人员"], lines: [
      ["Where can I find the building service desk?", "大楼服务台在哪里？"],
      ["It's beside the loading entrance.", "它在货物入口旁边。"],
      ["I need to report a door that won't close.", "我想报告一扇关不上的门。"],
      ["Please tell me its floor and room number.", "请告诉我楼层和房间号码。"],
      ["It's on level four, near the plant room.", "它在四楼，靠近设备间。"],
      ["Thank you. I'll send the location to the technician.", "谢谢，我会把位置发给维修技术员。"],
    ] },
  ],
  "supermarket-produce-department": [
    { title: "挑选水果与称重", roles: ["顾客", "店员"], lines: [
      ["Are these pears ready to eat today?", "这些梨今天就能吃吗？"],
      ["The softer ones are ready; the firm ones need more time.", "软一些的已经可以吃，硬一些的还要放一放。"],
      ["Could I have three ripe pears?", "我能拿三个熟一点的梨吗？"],
      ["Of course. I'll put them in a paper bag.", "当然，我帮您装进纸袋。"],
      ["Where can I weigh these apples?", "这些苹果在哪里称重？"],
      ["Use the scale beside the produce sign.", "请用水果蔬菜标牌旁边的秤。"],
    ] },
    { title: "询问蔬菜与香草", roles: ["顾客", "店员"], lines: [
      ["Do you have fresh basil today?", "你们今天有新鲜罗勒吗？"],
      ["Yes, it's on the lower shelf beside the mint.", "有，在下层架子上，薄荷旁边。"],
      ["I only need a small bunch.", "我只需要一小把。"],
      ["You can take one from this basket.", "您可以从这个篮子里拿一把。"],
      ["Are these tomatoes sold by weight?", "这些西红柿是按重量卖的吗？"],
      ["Yes. Please put them on the scale over there.", "是的，请把它们放到那边的秤上。"],
    ] },
  ],
  "supermarket-checkout-station": [
    { title: "付款与装袋", roles: ["顾客", "收银员"], lines: [
      ["Can I pay for these with contactless?", "我可以用非接触方式付款吗？"],
      ["Yes. Tap your card when the screen asks.", "可以，屏幕提示时请感应银行卡。"],
      ["I brought a reusable bag. Can I use it?", "我带了一个环保袋，可以用吗？"],
      ["Certainly. Place it in the bagging area, please.", "当然可以，请把它放在装袋区。"],
      ["Where should I put my items?", "我应该把商品放在哪里？"],
      ["You can put them beside the card reader.", "您可以把它们放在刷卡机旁边。"],
    ] },
    { title: "处理价格疑问", roles: ["顾客", "收银员"], lines: [
      ["This item has a different price on the shelf.", "这个商品在货架上标的价格不一样。"],
      ["I'll ask a supervisor to check the shelf label.", "我请主管核对一下货架标签。"],
      ["Do I need to move to another lane?", "我需要换到另一条队伍吗？"],
      ["No, you can stay here while we check.", "不用，核对时您可以留在这里。"],
      ["Can I scan my loyalty card now?", "我现在可以扫描会员卡吗？"],
      ["Yes. Please scan it before you pay.", "可以，请在付款前扫描。"],
    ] },
  ],
};
